version: '3.8'

services:

  postgres:
      restart: always
      image: postgis/postgis
      container_name: pgsql
      environment:
        - POSTGRES_DB=raw
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin
      ports:
        - '5434:5432'
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
        - ./tests/fixtures/pokhara.sql:/docker-entrypoint-initdb.d/pokhara.sql

  redis:
    image: redis
    container_name: redis
    ports:
     - "6379:6379"

  app:
    build: .
    container_name: api
    command: uvicorn API.main:app --reload --host 0.0.0.0 --port 8000 --no-use-colors --proxy-headers
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres

  worker:
    build: .
    container_name: worker
    command: celery --app API.api_worker worker --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - app
      - redis
      - postgres


  worker-dashboard:
    build: .
    container_name: flower
    command:  celery --broker=redis://redis:6379// --app API.api_worker flower --address=0.0.0.0 --port=5000
    ports:
      - 5000:5000
    depends_on:
      - app
      - redis
      - worker