name: black-action
on:
  pull_request:
    paths-ignore:
      - 'infra/**'
    branches:
      - master
      - develop
jobs:
  linter_name:
    name: runner / black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: ". --check"